<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml" lang="en">
      <head>
        <title>XML Sitemap — UniqueDigit Portal</title>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: #FAFAFA;
            color: #0F172A;
            line-height: 1.6;
            margin: 0;
            padding: 2rem 1rem;
          }
          .container {
            max-width: 1000px;
            margin: 0 auto;
            background: #FFFFFF;
            padding: 2.5rem;
            border-radius: 1.5rem;
            border: 1px solid #E2E8F0;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
          }
          .header {
            border-bottom: 2px solid #F1F5F9;
            padding-bottom: 1.5rem;
            margin-bottom: 2rem;
          }
          .badge {
            display: inline-block;
            background: #EEF2FF;
            color: #4F46E5;
            padding: 0.25rem 0.75rem;
            border-radius: 9999px;
            font-size: 0.75rem;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            margin-bottom: 0.75rem;
          }
          h1 {
            margin: 0 0 0.5rem 0;
            font-size: 1.75rem;
            font-weight: 800;
            color: #0F172A;
          }
          p.subtitle {
            margin: 0;
            color: #64748B;
            font-size: 0.95rem;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 1.5rem;
            font-size: 0.875rem;
          }
          th {
            text-align: left;
            padding: 0.75rem 1rem;
            background: #F8FAFC;
            color: #475569;
            font-weight: 700;
            border-bottom: 2px solid #E2E8F0;
            font-size: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
          }
          td {
            padding: 0.85rem 1rem;
            border-bottom: 1px solid #F1F5F9;
            color: #334155;
          }
          tr:hover td {
            background: #F8FAFC;
          }
          a {
            color: #4F46E5;
            text-decoration: none;
            font-weight: 600;
            word-break: break-all;
          }
          a:hover {
            text-decoration: underline;
          }
          .priority-high {
            background: #ECFDF5;
            color: #059669;
            padding: 0.15rem 0.5rem;
            border-radius: 0.375rem;
            font-weight: 700;
            font-size: 0.75rem;
          }
          .priority-med {
            background: #EFF6FF;
            color: #2563EB;
            padding: 0.15rem 0.5rem;
            border-radius: 0.375rem;
            font-weight: 700;
            font-size: 0.75rem;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <span class="badge">🗺️ Google-Compliant Sitemap</span>
            <h1>XML Sitemap Index</h1>
            <p class="subtitle">
              Total Indexed URLs: <strong><xsl:value-of select="count(/sitemap:urlset/sitemap:url)"/></strong> • Generated by UniqueDigit SEO Engine
            </p>
          </div>
          <table>
            <thead>
              <tr>
                <th style="width: 55%;">URL Location</th>
                <th style="width: 15%;">Priority</th>
                <th style="width: 15%;">Change Frequency</th>
                <th style="width: 15%;">Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="/sitemap:urlset/sitemap:url">
                <tr>
                  <td>
                    <a>
                      <xsl:attribute name="href">
                        <xsl:value-of select="sitemap:loc"/>
                      </xsl:attribute>
                      <xsl:value-of select="sitemap:loc"/>
                    </a>
                  </td>
                  <td>
                    <span>
                      <xsl:attribute name="class">
                        <xsl:choose>
                          <xsl:when test="sitemap:priority &gt;= 0.9">priority-high</xsl:when>
                          <xsl:otherwise>priority-med</xsl:otherwise>
                        </xsl:choose>
                      </xsl:attribute>
                      <xsl:value-of select="sitemap:priority"/>
                    </span>
                  </td>
                  <td><xsl:value-of select="sitemap:changefreq"/></td>
                  <td><xsl:value-of select="sitemap:lastmod"/></td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
